name: Publish

on:
  push:
    branches:
      - main
    paths:
      - 'Juriba.AppM/**'

jobs:
  publishpsgallery:
    name: 'PowerShell Gallery'
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGETAPIKEY }}
    steps:
      - uses: actions/checkout@v4
      - shell: pwsh
        run: Publish-Module -Path .\Juriba.AppM -NuGetApiKey $env:NUGET_API_KEY -Verbose